# Generated by Django 4.2.7 on 2023-11-09 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_slug_to_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='unitprice',
            new_name='unit_price',
        ),
    ]
